=== einomies/HH-XML-SWD4TA011-12/Oppimistehtava_03_JAXB/henkilosto.xsd
<?xml version="1.0" encoding="ISO-8859-15"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="henkilosto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="henkilo" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="hetu" type="xs:string"/>
							<xs:element name="nimi">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="sukunimi" type="xs:string"/>
										<xs:element name="etunimi" type="xs:string" maxOccurs="3"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="osoite" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="lahiosoite" type="xs:string" minOccurs="0"/>
										<xs:element name="postinumero" type="xs:string"/>
										<xs:element name="postitoimipaikka" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="tiimi" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="nimi" type="xs:string" use="required"/>
									<xs:attribute name="asema" type="xs:string" default="jäsen"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" type="xs:string"/>
							<xs:element name="puhelin" maxOccurs="3">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type" type="xs:string" default="työ"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="nimike" type="xs:string"/>
							<xs:element name="tyohuone" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="sijainti" type="xs:string" default="Helia1"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="tunnus" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="paivitetty" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== einomies/HH-XML-SWD4TA011-12/Oppimistehtava_02_XSLT/henkilosto.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<henkilosto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="henkilosto.xsd">
	<henkilo  tunnus="marsi">
		<hetu>123456-123A</hetu>
		<nimi>
			<sukunimi>Marttila</sukunimi>
			<etunimi>Sirpa</etunimi>
		</nimi>
		<osoite>
			<lahiosoite>Ratapihantie 13</lahiosoite>
			<postinumero>00520</postinumero>
			<postitoimipaikka>HELSINKI</postitoimipaikka>
		</osoite>
		<tiimi nimi="Tiedonhallinta" asema="jäsen"/>
		<email>sirpa.marttila@haaga-helia.fi</email>
		<puhelin type="keskus">09 229 611</puhelin>
		<puhelin>040 488 7288</puhelin>
		<nimike>Lehtori</nimike>
	</henkilo>
	<henkilo tunnus="jaami">
		<hetu>123456-123B</hetu>
		<nimi>
			<sukunimi>Jakkola</sukunimi>
			<etunimi>Mirja</etunimi>
		</nimi>
		<email>mirja.jaakkola@haaga-helia.fi</email>
		<puhelin>040 488 7267</puhelin>
		<nimike>Lehtori</nimike>
		<tyohuone sijainti="Helia1">6031</tyohuone>
	</henkilo>
	<henkilo tunnus="ulpel">
		<hetu>123456-123C</hetu>
		<nimi>
			<sukunimi>Ulpovaara</sukunimi>
			<etunimi>Elina</etunimi>
		</nimi>
		<email>elina.ulpvaara@haaga-helia.fi</email>
		<puhelin>040 488 7282</puhelin>
		<nimike>Lehtori</nimike>
		<tyohuone sijainti="Helia1">6031</tyohuone>
	</henkilo>
	<henkilo tunnus="kivha">
		<hetu>123456-123E</hetu>
		<nimi>
			<sukunimi>Kivihalme</sukunimi>
			<etunimi>Minna</etunimi>
		</nimi>
		<email>minna.kivihalemi@haaga-helia.fi</email>
		<puhelin>050 310 4017</puhelin>
		<nimike>Koulutusohjelmajohtaja</nimike>
	</henkilo>
	<henkilo tunnus="lehpa">
		<hetu>123456-123F</hetu>
		<nimi>
			<sukunimi>Lehessalo</sukunimi>
			<etunimi>Paavo</etunimi>
		</nimi>
		<email>paavo.lehessalo@haaga-helia.fi</email>
		<puhelin>050 310 0634</puhelin>
		<nimike>Koulutusohjelmajohtaja</nimike>
	</henkilo>
</henkilosto>
